#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIEUCHUYENNV
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="DNNLocal")]
	public partial class DIEUCHUYENNVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DIEUCHUYENNVDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SiteSqlServer"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DIEUCHUYENNVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DIEUCHUYENNVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DIEUCHUYENNVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DIEUCHUYENNVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.SP_DIEUCHUYEN_NV")]
		public ISingleResult<SP_DIEUCHUYEN_NVResult> SP_DIEUCHUYEN_NV([Parameter(DbType="Int")] System.Nullable<int> idImployee)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idImployee);
			return ((ISingleResult<SP_DIEUCHUYEN_NVResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_DIEUCHUYEN_NVResult
	{
		
		private int _Id;
		
		private int _EmployeeId;
		
		private System.Nullable<int> _UnitId;
		
		private string _EmpCode;
		
		private string _Department;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<int> _PositionId;
		
		private string _Desicion;
		
		private System.Nullable<System.DateTime> _DesicionDate;
		
		private string _AttachFile;
		
		private System.Nullable<int> _Editor;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		private string _IP;
		
		public SP_DIEUCHUYEN_NVResult()
		{
		}
		
		[Column(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[Column(Storage="_EmployeeId", DbType="Int NOT NULL")]
		public int EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this._EmployeeId = value;
				}
			}
		}
		
		[Column(Storage="_UnitId", DbType="Int")]
		public System.Nullable<int> UnitId
		{
			get
			{
				return this._UnitId;
			}
			set
			{
				if ((this._UnitId != value))
				{
					this._UnitId = value;
				}
			}
		}
		
		[Column(Storage="_EmpCode", DbType="NChar(12)")]
		public string EmpCode
		{
			get
			{
				return this._EmpCode;
			}
			set
			{
				if ((this._EmpCode != value))
				{
					this._EmpCode = value;
				}
			}
		}
		
		[Column(Storage="_Department", DbType="NVarChar(50)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[Column(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[Column(Storage="_PositionId", DbType="Int")]
		public System.Nullable<int> PositionId
		{
			get
			{
				return this._PositionId;
			}
			set
			{
				if ((this._PositionId != value))
				{
					this._PositionId = value;
				}
			}
		}
		
		[Column(Storage="_Desicion", DbType="NVarChar(150)")]
		public string Desicion
		{
			get
			{
				return this._Desicion;
			}
			set
			{
				if ((this._Desicion != value))
				{
					this._Desicion = value;
				}
			}
		}
		
		[Column(Storage="_DesicionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DesicionDate
		{
			get
			{
				return this._DesicionDate;
			}
			set
			{
				if ((this._DesicionDate != value))
				{
					this._DesicionDate = value;
				}
			}
		}
		
		[Column(Storage="_AttachFile", DbType="NVarChar(300)")]
		public string AttachFile
		{
			get
			{
				return this._AttachFile;
			}
			set
			{
				if ((this._AttachFile != value))
				{
					this._AttachFile = value;
				}
			}
		}
		
		[Column(Storage="_Editor", DbType="Int")]
		public System.Nullable<int> Editor
		{
			get
			{
				return this._Editor;
			}
			set
			{
				if ((this._Editor != value))
				{
					this._Editor = value;
				}
			}
		}
		
		[Column(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this._ModifiedDate = value;
				}
			}
		}
		
		[Column(Storage="_IP", DbType="NChar(20)")]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this._IP = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
